# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-python-versions

      - run:
          name: install Python versions
          command: |
            [ ! -d "/home/circleci/.pyenv" ] && curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install 3.5.4 --skip-existing
            pyenv install 3.6.3 --skip-existing
            pyenv global 3.6.3 3.5.4
            echo "Installed Python versions"

      - save_cache:
          paths:
            - /home/circleci/.pyenv/
          key: v1-python-versions

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "requirements_dev.txt" }}

      - run:
          name: install dependencies
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            pip install tox
            tox -vv --notest

      - save_cache:
          paths:
            - ./.tox/
          key: v3-dependencies-{{ checksum "requirements_dev.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports